ATTACK_ITERATIONS_COUNT: 100
KEY_GENERATION:
  E_MAX_LENGTH: 1500
  E_OPTIONS_MAX_COUNT: 5
  FIRST_SAMPLE_MAX_SIZE: 5
  KEY_LENGTH: 1024
  MIDDLE_SAMPLE_MAX_SIZE: 20
  PRIME_MIN_LENGTH: 500
  THIRD_SAMPLE_MAX_SIZE: 5
STATS_ITERATIONS_COUNT: 100
