# note that all numbers will be floored as a precaution so inter your numbers as integer
KEY_GENERATION:
  KEY_LENGTH: 1024
  PRIME_MIN_LENGTH: 500
  FIRST_SAMPLE_MAX_SIZE: 5
  MIDDLE_SAMPLE_MAX_SIZE: 20
  THIRD_SAMPLE_MAX_SIZE: 5
  E_MAX_LENGTH: 1500
  E_OPTIONS_MAX_COUNT: 5